# reload tmux config file with <leader> + r
unbind r
bind r source-file ~/.tmux.conf

# set leader to Ctrl+Space
set -g prefix C-Space

# set count from 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# move between panes with <leader> + vim motions
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# options to make tmux more pleasant
set -g default-terminal 'tmux-256color'
set -g set-clipboard on
set -g status-interval 3
set -g mouse on

# tokyo night theme
set -g @plugin 'fabioluciano/tmux-tokyo-night'
set -g @theme_variation 'night'
set -g @theme_plugins 'datetime'
set -g @theme_plugin_datetime_format '%d/%m %H:%M'

# command for tmux plugin manager
run '~/.tmux/plugins/tpm/tpm'

# split with current path
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
