# Mouse mode:
set -g mouse on

# Set the base-index to 1 (rather than 0):
set -g base-index 1
set-window-option -g pane-base-index 1

# Automatically set window title:
set-window-option -g automatic-rename on
set-option -g set-titles on

# Change background color of a tab when activity occurs:
setw -g monitor-activity on

# Do not reset the color of the tab after activity stops:
setw -g monitor-silence 0

# Set status bar:
set -g status-justify centre

# VIM style navigation between panes:
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# 256 color:
set -g default-terminal "screen-256color"

# Set background color of active window to yellow:
set-window-option -g window-status-current-style bg=yellow

# Easy config reload:
bind-key r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"
